"""rename department

Revision ID: 147e70249316
Revises: 7ff9e4961199
Create Date: 2025-08-10 02:54:58.419066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '147e70249316'
down_revision = '7ff9e4961199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
